services:
  container:
    build:
      context: ./container
    ports:
      - "3000:3000"
    networks:
      - teddynet

  components:
    build:
      context: ./components
    ports:
      - "3001:3001"
    networks:
      - teddynet

networks:
  teddynet:
    driver: bridge
